openapi: 3.0.0
info:
  title: Notes API
  description: API for managing notes with sentiment analysis.
  version: 1.0.0

paths:
  /auth/login:
post:
summary: Log in
description: Log in to the system and obtain a JWT token for authentication.
parameters:
  - name: body
    in: body
    required: true
    schema:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
responses:
  200:
    description: User logged in successfully and token provided
    schema:
      type: object
      properties:
        token:
          type: string
          description: JWT token for authentication
        message:
          type: string
          description: Login success message
  400:
    description: Bad Request - Invalid username or password
    schema:
      type: object
      properties:
        error:
          type: string
          description: Description of the error
  404:
    description: Not Found - User not found
    schema:
      type: object
      properties:
        error:
          type: string
          description: Description of the error
  500:
    description: Internal Server Error
    schema:
      type: object
      properties:
        error:
          type: string
          description: Description of the error
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
