openapi: 3.0.0
info:
  title: Notes API
  description: API for managing notes with sentiment analysis.
  version: 1.0.0

paths:
  /auth/profile:
get:
summary: Retreive Profile
description: Retreive the profile of the user.
security:
  - BearerAuth: []
parameters:
  - name: Authorization
    in: header
    required: true
    schema:
      type: string
      description: Bearer token for authentication
      example: '<your_token>'
responses:
  200:
    description: Profile retreived successfully
    schema:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the user
        username:
          type: string
          description: Username of the user
        score_tag:
          type: string
          description: Polarity of the element
        agreement:
          type: string
          description: Marks the agreement between the sentiments detected in the text.
        subjectivity:
          type: string
          description: Marks the subjectivity of the text.
        confidence:
          type: string
          description: represents the confidence associated with the sentiment analysis performed on the text.
  401:
    description: Unauthorized - Authentication required or invalid token
    schema:
      type: object
      properties:
        error:
          type: string
          description: Description of the error
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT