openapi: 3.0.0
info:
  title: Notes API
  description: API for managing notes with sentiment analysis.
  version: 1.0.0

paths:
  /auth/register:
post:
summary: Register
description: Register to the system and obtain a JWT token for authentication.
parameters:
  - name: body
    in: body
    required: true
    schema:
      type: object
      properties:
        username:
          type: string
          example: "user1"
        password:
          type: string
          example: "password123"
responses:
  201:
    description: User registered in successfully and token provided
    schema:
      type: object
      properties:
        token:
          type: string
          description: JWT token for authentication
        message:
          type: string
          description: Register success message
  400:
    description: Username already exists or bad request
    schema:
      type: object
      properties:
        error:
          type: string
          description: Description of the error
  500:
    description: Internal Server Error
    schema:
      type: object
      properties:
        error:
          type: string
          description: Description of the error
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT